### PR TITLE
chore(supernova): fix typescript migration leftovers in supernova

### LINKED ISSUE #767: (Supernova): Fix all typescript migration leftovers for Libs
**Fix all typescript migration leftovers for Regions**

**Sub-tasks**
Please have a look on all regions/* folder and fix related files, this is aprx, files and count of errors:

- [x]  3  src/lib/createAlertsSlice.test.tsx:7
- [x]  5  src/lib/createAlertsSlice.tsx:6
- [x]  2  src/lib/createFiltersSlice.test.tsx:7
- [x]  3  src/lib/createFiltersSlice.tsx:6
- [x] 13  src/lib/createSilencesSlice.test.tsx:7
- [x]  3  src/lib/createSilencesSlice.tsx:147

**Additional Context**
Sometimes you will need to fix few other staff, try to minimaze it,  keep PRs small and easy to review.

### LINKED ISSUE #768: (Supernova): Fix all typescript migration leftovers for Lint Rules
**Fix all typescript migration leftovers for Eslint**

**Sub-tasks**
Please have a look on all project under supernova/  and fix related files, this is aprx, files and count of errors:

- [ ] "@typescript-eslint/no-unsafe-assignment": "off",
- [ ] "@typescript-eslint/no-unsafe-call": "off",
- [ ] "@typescript-eslint/no-unsafe-argument": "off",
- [ ] "@typescript-eslint/no-unsafe-return": "off",
- [ ] "@typescript-eslint/no-unsafe-member-access": "off",
- [ ] "@typescript-eslint/no-floating-promises": "off",
- [ ] "no-unused-vars": "off",
- [ ] "@typescript-eslint/restrict-plus-operands": "off",
- [ ] "react/no-unescaped-entities": "off",
- [ ] "@typescript-eslint/await-thenable": "off",
- [ ] "react/prop-types": "off",
- [x] "prefer-const": "off",
- [ ] "react/jsx-no-comment-textnodes": "off",

**Additional Context**
Sometimes you will need to fix few other staff, try to minimaze it,  keep PRs small and easy to review.
If it will be too big maybe make sense to split it to seprate PRs

### LINKED ISSUE #769: (Supernova): Fix all typescript migration leftovers for Silences
**Fix all typescript migration leftovers for Silences**

**Sub-tasks**
Please have a look on all silences/* folder and fix related files, this is aprx, files and count of errors:

- [x]  8  src/components/silences/CreateSilence.tsx:39
- [x]  6  src/components/silences/ExpireSilence.tsx:13
- [x]  4  src/components/silences/RecreateSilence.tsx:121
- [x]  1  src/components/silences/silenceHelpers.ts:46
- [x] 25  src/components/silences/SilenceScheduled.tsx:7
- [x]  6  src/components/silences/SilencesList.tsx:41
- [x]  4  src/components/StoreProvider.tsx:7
- [x]  1  src/helpers.ts:9

**Additional Context**
Sometimes you will need to fix few other staff, try to minimaze it, keep PRs small and easy to review.

### PR DESCRIPTION
**Pull request by TilmanHaupt**
# Summary

closes #769 
closes #768
closes #767 

Also deleted other leftover ts-ignores in supernova and 2 related expected errors in heureka.
Problems with endlessScrollList, ReactQuery fetches and Url-State-Provider are in #786

# Changes

Get rid of ts-ignores by installing luxon, importing used functions, typing, deleting unused code, use of functions like .getTime() for objects

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.
- [x] I have created a changeset for my changes.

# PR Manifesto

Review the [PR Manifesto](https://github.com/cloudoperators/juno/blob/main/docs/pr_manifesto.md) for best practises.

### CODE REVIEW

File: apps/supernova/src/components/silences/CreateSilence.tsx [hunk 1]
```diff
@@ -67,26 +62,22 @@ const errorHelpText = (messages: any) => {
...
   const excludedLabels = useSilencesExcludedLabels()
-  // @ts-ignore
   const { getMappingSilences, setSilences } = useSilencesActions()
   const enrichedLabels = useAlertEnrichedLabels()
   const user = useGlobalsUsername()
   const [displayNewSilence, setDisplayNewSilence] = useState(false)
   const [formState, setFormState] = useState(DEFAULT_FORM_VALUES)
   const [expirationDate, setExpirationDate] = useState(null)
-  const [showValidation, setShowValidation] = useState({})
-  const [error, setError] = useState(null)
```
Comment (TilmanHaupt) [inline apps/supernova/src/components/silences/CreateSilence.tsx:83]: Info: Error war actually never set.

File: apps/supernova/src/components/silences/CreateSilence.tsx [hunk 2]
```diff
@@ -67,26 +62,22 @@ const errorHelpText = (messages: any) => {
...
+  const [showValidation, setShowValidation] = useState<Record<string, string[]>>({})
   const { addMessage } = useActions()
 
   const silences = useSilencesItems()
 
-  const [success, setSuccess] = useState(null)
```
Comment (TilmanHaupt) [inline apps/supernova/src/components/silences/CreateSilence.tsx:88]: Info: The success messages are not shown in modal for one month, the modal is closed and message shown

File: apps/supernova/src/components/silences/RecreateSilence.tsx [hunk 3]
```diff
@@ -67,15 +61,13 @@ const RecreateSilence = (props: any) => {
...
 
   const silences = useSilencesItems()
-  // @ts-ignore
   const { setSilences } = useSilencesActions()
 
   const queryClient = useQueryClient()
 
   const [displayNewSilence, setDisplayNewSilence] = useState(false)
   const [formState, setFormState] = useState(DEFAULT_FORM_VALUES)
-  const [expirationDate, setExpirationDate] = useState(null)
```
Comment (TilmanHaupt) [inline apps/supernova/src/components/silences/RecreateSilence.tsx:77]: Expiration Date was never actually set because no Alert was given on line 100. There is no simelar useable func

File: apps/supernova/src/components/silences/silenceHelpers.ts [hunk 4]
```diff
@@ -4,35 +4,32 @@
  */
 
 export const DEFAULT_DURATION_OPTIONS = [
```
Comment (TilmanHaupt) [inline apps/supernova/src/components/silences/silenceHelpers.ts:6]: Used number and not string and just cast to string in select.

File: apps/supernova/src/components/silences/silenceScheduledHelpers.ts [hunk 5]
```diff
@@ -3,24 +3,6 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
-export const DEFAULT_FORM_VALUES = {
```
Comment (TilmanHaupt) [inline apps/supernova/src/components/silences/silenceScheduledHelpers.ts:6]: Now in silenceScheduled Modal

File: apps/supernova/src/lib/createAlertsSlice.test.tsx [hunk 6]
```diff
@@ -39,25 +39,5 @@ describe("createAlertsSlice", () => {
...
-          itemsFiltered: useAlertsItemsFiltered(),
-        }),
-        { wrapper }
-      )
-
-      let mock: any
-
-      act(() => {
-        // @ts-ignore
-        store.result.current.actions.setFilteredItems(mock)
```
Comment (TilmanHaupt) [inline apps/supernova/src/lib/createAlertsSlice.test.tsx:57]: Sets nothing in filters items and is then true because enrichedLabels is nothing bc undefined.

File: apps/supernova/src/App.tsx [hunk 7]
```diff
@@ -80,7 +79,7 @@ const AppWithNewUrlStructure = (props: any) => {
 
 const StyledApp = (props: any) => {
   return (
-    // @ts-ignore
+    // @ts-ignore > need to validate if theme is part of theme-types
```
Comment (barsukov) [inline apps/supernova/src/App.tsx:82]: 1) Please remove this line
2) Please run typececk
3) copy error number and message
4) paste instead with @ts-expect-error

File: apps/supernova/src/api/silences.ts [hunk 8]
```diff
@@ -51,7 +51,7 @@ export const deleteSilences = async (variables: any) => {
   }
 }
 
-export const createSilences = async (variables: any) => {
+export const createSilences = async (variables: Record<string, any>): Promise<any> => {
```
Comment (barsukov) [inline apps/supernova/src/api/silences.ts:54]: please Response intead of any.

File: apps/supernova/src/components/alerts/AlertSilences.tsx [hunk 9]
```diff
@@ -19,33 +19,30 @@ import { useAlertsActions, useGlobalsActions, useSilencesActions } from "../Stor
...
+  const { addMessage } = useActions()
 
   // fetch silences
   const { error, data, isLoading } = useBoundQuery("silences")
 
   useEffect(() => {
     if (data) {
       setSilences({
-        // @ts-expect-error TS(2339) FIXME: Property 'silences' does not exist on type 'any'.
+        // @ts-ignore
```
Comment (barsukov) [inline apps/supernova/src/components/alerts/AlertSilences.tsx:37]: Please rollback

**Review by barsukov — CHANGES_REQUESTED** [review]
Very good job few comments please fix and we are good to go!

**Review by taymoor89 — APPROVED** [review]
