### PR TITLE
fix(supernova): activeFilters are not rendered if value is not an array

### LINKED ISSUE #609: [BUG](supernova): Non array values in FilterPills lead to failed render

### PR DESCRIPTION
**Pull request by TilmanHaupt**
# Summary
Fix issue where activeFilters are not rendered if the value is not an array. Closes #609

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.

### CODE REVIEW

File: apps/supernova/src/components/filters/FilterPills.jsx [hunk 1]
```diff
@@ -30,28 +30,30 @@ const FilterPills = () => {
...
-            <Pill
-              pillKey={key}
-              pillValue={item}
-              closeable
-              onClose={() => deleteFilter(key, item)}
-              key={`${key}:${item}`}
-              onClick={() => pauseFilter(key, item)}
-            />
+        if (Array.isArray(filterItems)) {
+          return filterItems.map((item) =>
```
Comment (guoda-puidokaite) [inline apps/supernova/src/components/filters/FilterPills.jsx:34]: Ah! `Map` was being called directly, assuming an array. 🙈

Slightly cleaner way to do this:
```suggestion
          return filterItems?.map((item) =>
```

**Review by guoda-puidokaite — COMMENTED** [review]
Nice catch, just slight suggestion.

**Review by guoda-puidokaite — CHANGES_REQUESTED** [review]
Could we add a unit test to cover this bug for the future?

**Comment by guoda-puidokaite** [comment]
> Could we add a unit test to cover this bug for the future?

Sorry, already done

File: apps/supernova/src/components/filters/FilterPills.jsx [hunk 2]
```diff
@@ -30,28 +30,30 @@ const FilterPills = () => {
...
+            pausedFilters[key]?.includes(item) ? (
+              <Pill
+                className="bg-theme-background-lvl-4 opacity-70	"
```
Comment (guoda-puidokaite) [inline apps/supernova/src/components/filters/FilterPills.jsx:37]: Tiny 😅

```suggestion
                className="bg-theme-background-lvl-4 opacity-70"
```

File: apps/supernova/src/components/filters/FilterPills.jsx [hunk 3]
```diff
@@ -30,28 +30,30 @@ const FilterPills = () => {
...
-          ) : (
-            <Pill
-              pillKey={key}
-              pillValue={item}
-              closeable
-              onClose={() => deleteFilter(key, item)}
-              key={`${key}:${item}`}
-              onClick={() => pauseFilter(key, item)}
-            />
+        if (Array.isArray(filterItems)) {
```
Comment (guoda-puidokaite) [inline apps/supernova/src/components/filters/FilterPills.jsx:33]: This line would then be unnecessary with optional mapping

```suggestion
        if (Array.isArray(filterItems)) {
```

Comment (guoda-puidokaite) [reply apps/supernova/src/components/filters/FilterPills.jsx:33]: Up to you which way you prefer. I just like the consistency and shortness of the optional solution.

File: apps/supernova/src/components/filters/FilterPills.jsx (hunk 1 above)
Comment (ArtieReus) [reply apps/supernova/src/components/filters/FilterPills.jsx]: I like this way looks cleaner

File: .changeset/clean-plums-notice.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@cloudoperators/juno-app-supernova": patch
```
Comment (hodanoori) [inline .changeset/clean-plums-notice.md:2]: Shouldn't you add a patch changeset also for greenhouse?

**Review by ArtieReus — APPROVED** [review]
lgtm

**Review by hodanoori — DISMISSED** [review]
LGTM

**Review by ArtieReus — APPROVED** [review]
lgtm

File: apps/supernova/src/lib/createFiltersSlice.jsx [hunk 5]
```diff
@@ -28,11 +28,21 @@ const parsePredefinedFilters = (predefinedFilters) => {
...
+    if (Array.isArray(value)) {
+      acc[key] = value // valid key-value pair
+    } else {
+      console.warn(`[supernova]::parseInitialFilters: Value for "${key}" is not an Array.`)
+    }
+    return acc
+  }, {})
+
   // Check if all keys are in filterLabelValues
   if (!Object.keys(initialFilters).every((key) => filterLabels.includes(key))) {
```
Comment (guoda-puidokaite) [inline apps/supernova/src/lib/createFiltersSlice.jsx:47]: **(Non-blocking concerns)**

Concerned that there's other string/array methods in this file that don't check valid type before executing e.g. `.included`.
Your changes look good, but if we've the time (even in a follow-up) PR would be great to ensure that we prevent the same issue causing bugs, at least in the same files.

File: apps/supernova/src/lib/createFiltersSlice.jsx [hunk 6]
```diff
@@ -28,11 +28,21 @@ const parsePredefinedFilters = (predefinedFilters) => {
 const parseInitialFilters = (initialFilters, filterLabels) => {
   if (!initialFilters) return initialFiltersState.initialFilters
 
-  if (typeof initialFilters !== "object") {
+  if (typeof initialFilters !== "object" || initialFilters === null) {
```
Comment (guoda-puidokaite) [inline apps/supernova/src/lib/createFiltersSlice.jsx:31]: **(Non-blocking suggestion)**

Safer coverage?

```suggestion
  if (!initialFilters || typeof initialFilters !== "object")
```

Comment (TilmanHaupt) [reply apps/supernova/src/lib/createFiltersSlice.jsx:31]: its not safer because undefined is not an object.

Comment (ArtieReus) [reply apps/supernova/src/lib/createFiltersSlice.jsx:31]: cool @guoda-puidokaite 

!initialFilters checks if initialFilters is falsy (i.e., null, undefined, false, 0, NaN, or an empty string).

Comment (guoda-puidokaite) [reply apps/supernova/src/lib/createFiltersSlice.jsx:31]: > its not safer because undefined is not an object.

Not sure what you mean by this? I just think additionally to checking for `null`, we could cover all `falsy` values. But maybe not necessary here. You know code more @TilmanHaupt @ArtieReus

File: apps/supernova/src/lib/createFiltersSlice.jsx (hunk 5 above)
Comment (TilmanHaupt) [reply apps/supernova/src/lib/createFiltersSlice.jsx:47]: I see none. At least on the surface everything is tested. Maybe there are like here this problems in nested forms.

File: apps/supernova/src/lib/createFiltersSlice.jsx [hunk 7]
```diff
@@ -28,11 +28,21 @@ const parsePredefinedFilters = (predefinedFilters) => {
...
     console.warn("[supernova]::parseInitialFilters: initialFilters object is not an object")
     return {}
   }
 
+  // Check if all values are arrays
+  initialFilters = Object.entries(initialFilters).reduce((acc, [key, value]) => {
```
Comment (guoda-puidokaite) [inline apps/supernova/src/lib/createFiltersSlice.jsx:37]: **(Non-blocking suggestion)**

Good solution, wonder if this would be more readable instead of manually constructing key-value pairs. But please merge as you want as we need to do this fast, no problem.

```suggestion
  initialFilters = Object.fromEntries(
    Object.entries(initialFilters).filter(([key, value]) => {
      const isArray = Array.isArray(value)
      if (!isArray) {
        console.warn(`[supernova]::parseInitialFilters: Value for "${key}" is not an Array.`)
      }
      return isArray
    })
  )
```

File: apps/supernova/src/lib/createFiltersSlice.jsx (hunk 6 above)
Comment (TilmanHaupt) [reply apps/supernova/src/lib/createFiltersSlice.jsx:31]: All other values are not objects.

**Review by andypf — APPROVED** [review]
👍

File: apps/supernova/src/lib/createFiltersSlice.jsx (hunk 6 above)
Comment (guoda-puidokaite) [reply apps/supernova/src/lib/createFiltersSlice.jsx:31]: Ahhh, duh. Nice.
